#!/usr/bin/env bash

### certmaker Usage:help
#
# Tool to generate a CA, generate keys and CSRs, and sign CSRs
#
# Create a new CA:
#
#     certmaker new ca CONFFILE
#
# Create a new host profile:
#
#     certmaker new host HOST
#
# Sign a named host:
#
#     certmaker sign HOST
#
# Sign a CSR:
#
#     certmaker sign CSRFILE
#
###/doc

#%include safe.sh autohelp.sh out.sh
#%include ctconf.sh template.sh ca.sh sign.sh files.sh host.sh new.sh renew.sh

cm:main() {
    # Do not autohelp:check here, as it would override sub-topic help
    [[ -n "$*" ]] || {
        autohelp:print
        exit 0
    }
    action="$1"; shift || :

    cm:config:load_config

    case "$action" in
        template)
            cm:template "$@"
            ;;
        new)
            cm:new "$@"
            ;;
        edit)
            cm:host:edit-host "$@"
            ;;
        sign)
            cm:sign "$@"
            ;;
        renew)
            cm:renew "$@"
            ;;
        help)
            autohelp:print
            exit 0
            ;;
        view)
            cm:view "$@"
            ;;
        *)
            autohelp:print
            out:fail "Unknown action $action"
            ;;
    esac
}

cm:helpcheck() {
    local section="$1"; shift

    [[ "$*" =~ --help ]] || return 0

    autohelp:print "$section"

    exit 0
}

cm:main "$@"
